### ISSUE TITLE
Cumulative breach - configure the period of time in which a cumulative breach occurs ?

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/msupply-cold-chain#88] opened 2021-04-21 01:31 UTC
Example: have a cumulative breach over 3 months makes no sense. Is there a way to specify the period to reset the cumulative breach data ?

**Comment by joshxg** [comment] 2021-04-22 07:35
The intended behaviour:

- The cumulative breach shown on the list view is for the period of time the list view is displaying temperatures (3 days).
- The cumulative breach shown in the detail view shows over the period defined by the date selector.

If the intended behaviour is not the actual behaviour please let us now. Otherwise, closing this one.

**Closed by joshxg** 2021-04-22 07:35 UTC
