### ISSUE TITLE
TESTING: Sync settings

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/msupply-cold-chain#41] opened 2021-04-13 09:33 UTC
# Sync settings tests

## Setup

- TODO.

## Test cases

- TODO.

**Comment by Chris-Petty** [comment] 2021-05-12 00:53
Seems like a duplicate of #39

**Comment by Chris-Petty** [comment] 2021-05-12 00:53
I can't read lol

**Closed** 2021-05-12 05:07 UTC
Labels: test template
